export type PastEvent = {
  date: string;
  title: string;
  venue: string;
  city: string;
  country: string;
  sourceUrl: string | null;
};

// Resident Advisor past-events pages 31 through 1, imported 4 September 2026.
// This archive begins with the earliest event currently listed by RA (March 2013).
export const raPastEvents: PastEvent[] = [
  {"date":"2013-03-14","title":"Sander Kleinenberg","venue":"Sound","city":"Los Angeles","country":"United States of America","sourceUrl":"https://ra.co/events/461113"},
  {"date":"2013-03-16","title":"Praia Urbana feat. Sander Kleinenberg, Fur Coat and Sarah Main","venue":"The Last Concert Cafe","city":"Houston","country":"United States of America","sourceUrl":"https://ra.co/events/453585"},
  {"date":"2013-03-16","title":"Praia Urbana","venue":"The Last Concert Cafe","city":"Houston","country":"United States of America","sourceUrl":"https://ra.co/events/456210"},
  {"date":"2013-03-17","title":"Toolroom Knights at UMF","venue":"Ultra Nightclub","city":"Miami","country":"United States of America","sourceUrl":"https://ra.co/events/458589"},
  {"date":"2013-03-19","title":"Sander Kleinenberg presents: This IS Day/Night","venue":"Delano Hotel","city":"Miami","country":"United States of America","sourceUrl":"https://ra.co/events/459630"},
  {"date":"2013-03-31","title":"Tribehouse Pres. Oster-Powerday","venue":"102","city":"Düsseldorf","country":"Germany","sourceUrl":"https://ra.co/events/454386"},
  {"date":"2013-04-30","title":"De Nachtkerk - Het Kroningsfestival","venue":"Paradiso","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/470056"},
  {"date":"2013-05-18","title":"Pacha Festival Amsterdam 2013","venue":"Java Eiland","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/441125"},
  {"date":"2013-05-19","title":"Groove Garden 2013 - Sunday","venue":"Zwembad De Nieuwe Hateboer","city":"All","country":"Netherlands","sourceUrl":"https://ra.co/events/448669"},
  {"date":"2013-05-23","title":"Welcome To Pacha 2013 - Armand Van Helden","venue":"Pacha Ibiza","city":"Ibiza","country":"Spain","sourceUrl":"https://ra.co/events/484169"},
  {"date":"2013-06-15","title":"Indian Summer Festival 2013 - Saturday","venue":"Geestmerambacht","city":"All","country":"Netherlands","sourceUrl":"https://ra.co/events/448754"},
  {"date":"2013-06-24","title":"Epica","venue":"Pacha Ibiza","city":"Ibiza","country":"Spain","sourceUrl":"https://ra.co/events/471433"},
  {"date":"2013-07-04","title":"Dance.Here.Now. present This Is Sander Kleinenberg","venue":"Cielo","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/492550"},
  {"date":"2013-07-15","title":"Monday Social with Sander Kleinenberg","venue":"Sound","city":"Los Angeles","country":"United States of America","sourceUrl":"https://ra.co/events/487835"},
  {"date":"2013-07-20","title":"Sander Kleinenberg, J.Remy & Bones ","venue":"Harlot","city":"San Francisco/Oakland","country":"United States of America","sourceUrl":"https://ra.co/events/500930"},
  {"date":"2013-07-21","title":"1st Annual Beach Party with Sander Kleinenberg","venue":"The Garden","city":"El Paso","country":"United States of America","sourceUrl":"https://ra.co/events/499644"},
  {"date":"2013-07-23","title":"Sander Kleineberg Presents: Superstars","venue":"Eden","city":"Ibiza","country":"Spain","sourceUrl":"https://ra.co/events/502882"},
  {"date":"2013-08-03","title":"Holi Festival Of Colours","venue":"Vredenburg Leidsche Rijn","city":"Utrecht","country":"Netherlands","sourceUrl":"https://ra.co/events/499713"},
  {"date":"2013-08-06","title":"Sander Kleineberg Presents: Superstars","venue":"Eden","city":"Ibiza","country":"Spain","sourceUrl":"https://ra.co/events/502883"},
  {"date":"2013-08-10","title":"Loveland Festival 2013","venue":"Sloterpark","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/450601"},
  {"date":"2013-08-13","title":"Sander Kleineberg Presents: Superstars","venue":"Eden","city":"Ibiza","country":"Spain","sourceUrl":"https://ra.co/events/502884"},
  {"date":"2013-10-16","title":"Amsterdam Dance Event - Day 1","venue":"TBA - Amsterdam","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/463939"},
  {"date":"2013-10-26","title":"Pure Pacha vs Cafe Mambo - Sander Kleinenberg Norman Doray","venue":"Pacha London","city":"London","country":"United Kingdom","sourceUrl":"https://ra.co/events/518218"},
  {"date":"2013-10-26","title":"Waxon WAX OFF Halloween Massacre Boat Party","venue":"Festival Pier","city":"London","country":"United Kingdom","sourceUrl":"https://ra.co/events/531433"},
  {"date":"2013-11-15","title":"Sander Kleinenberg","venue":"Harlot","city":"San Francisco/Oakland","country":"United States of America","sourceUrl":"https://ra.co/events/536633"},
  {"date":"2013-11-23","title":"Blackprint Pres: Sander Kleinenberg","venue":"NEST","city":"Toronto","country":"Canada","sourceUrl":"https://ra.co/events/541593"},
  {"date":"2013-11-25","title":"Monday Social Feat. Sander Kleinenberg","venue":"Sound","city":"Los Angeles","country":"United States of America","sourceUrl":"https://ra.co/events/538132"},
  {"date":"2013-12-20","title":"Release - China's Indoor Electronic Dance Music Experience","venue":"UCCA","city":"Beijing","country":"China","sourceUrl":"https://ra.co/events/541699"},
  {"date":"2014-02-14","title":"Sander Kleneinberg","venue":"Stereo","city":"Montreal","country":"Canada","sourceUrl":"https://ra.co/events/562669"},
  {"date":"2014-03-08","title":"Pacha Opening 2014: Sander Kleinenberg","venue":"Pacha","city":"Buenos Aires","country":"Argentina","sourceUrl":"https://ra.co/events/564898"},
  {"date":"2014-03-16","title":"The Podium Lounge Night 3","venue":"Ms Collins","city":"Melbourne","country":"Australia","sourceUrl":"https://ra.co/events/576757"},
  {"date":"2014-03-25","title":"Sander Kleinenberg - Exclusive 4 Hour set","venue":"FDR at Delano","city":"Miami","country":"United States of America","sourceUrl":"https://ra.co/events/578951"},
  {"date":"2014-03-30","title":"Sander Kleinenberg","venue":"Audio SF","city":"San Francisco/Oakland","country":"United States of America","sourceUrl":"https://ra.co/events/582284"},
  {"date":"2014-04-05","title":"Sander Kleinenberg","venue":"Pacha London","city":"London","country":"United Kingdom","sourceUrl":"https://ra.co/events/568307"},
  {"date":"2014-04-13","title":"Sounds Like Sundays with Trent Cantrelle Sander Kleinenberg","venue":"Room 86","city":"Los Angeles","country":"United States of America","sourceUrl":"https://ra.co/events/584519"},
  {"date":"2014-05-17","title":"Pacha Festival Amsterdam 2014","venue":"Java Eiland","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/555815"},
  {"date":"2014-05-25","title":"Sander Kleinenberg / Tom Trago / Justin Strauss / George Faya","venue":"Verboten","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/598876"},
  {"date":"2014-07-04","title":"Project301 with Sander Kleinenberg","venue":"301","city":"El Paso","country":"United States of America","sourceUrl":"https://ra.co/events/613315"},
  {"date":"2014-07-12","title":"Sander Kleinenberg","venue":"Castle","city":"Chicago","country":"United States of America","sourceUrl":"https://ra.co/events/613986"},
  {"date":"2014-07-21","title":"Monday Social Feat. Sander Kleinenberg","venue":"Sound","city":"Los Angeles","country":"United States of America","sourceUrl":"https://ra.co/events/603326"},
  {"date":"2014-08-02","title":"Sky City Festival","venue":"Arenapark","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/572324"},
  {"date":"2014-10-03","title":"No. 226 - Sander Kleinenberg","venue":"Club Bellevue","city":"Zurich","country":"Switzerland","sourceUrl":"https://ra.co/events/644298"},
  {"date":"2014-11-06","title":"All Gone To Sea - Miami Cruise","venue":"Carnival Victory","city":"Miami","country":"United States of America","sourceUrl":"https://ra.co/events/590450"},
  {"date":"2014-11-08","title":"Sander Kleinenberg","venue":"Space Ibiza NY","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/651132"},
  {"date":"2014-11-29","title":"Sander Kleinenberg","venue":"Pacha","city":"Buenos Aires","country":"Argentina","sourceUrl":"https://ra.co/events/659031"},
  {"date":"2015-03-06","title":"Come Together feat. Sander Kleinenberg","venue":"Rumor","city":"Philadelphia","country":"United States of America","sourceUrl":"https://ra.co/events/682081"},
  {"date":"2015-03-07","title":"Sound presents Sander Kleinenberg","venue":"Sound","city":"Los Angeles","country":"United States of America","sourceUrl":"https://ra.co/events/687190"},
  {"date":"2015-03-12","title":"Realmusic Events presents. Sander Kleinenberg","venue":"Kingdom Nightclub","city":"Austin","country":"United States of America","sourceUrl":"https://ra.co/events/682324"},
  {"date":"2015-03-14","title":"Relentless Beats presents Sander Kleinenberg","venue":"Monarch Theatre","city":"Phoenix","country":"United States of America","sourceUrl":"https://ra.co/events/692424"},
  {"date":"2015-03-14","title":"Fngrs Crssd presents: Crssd Festival","venue":"Waterfront Park in San Diego","city":"San Diego","country":"United States of America","sourceUrl":"https://ra.co/events/668035"},
  {"date":"2015-03-20","title":"Sander Kleinenberg","venue":"Space Ibiza NY","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/685657"},
  {"date":"2015-03-21","title":"Sander Kleinenberg at","venue":"Prime","city":"Boston","country":"United States of America","sourceUrl":"https://ra.co/events/695987"},
  {"date":"2015-03-27","title":"Love:Cure - Benefitting Beats Drop Cancer - Official WMC Event","venue":"Townhouse Hotel","city":"Miami","country":"United States of America","sourceUrl":"https://ra.co/events/688656"},
  {"date":"2015-04-30","title":"Sander Kleinenberg London DJ Residency","venue":"MODE","city":"London","country":"United Kingdom","sourceUrl":"https://ra.co/events/701292"},
  {"date":"2015-05-23","title":"Pacha Festival 2015","venue":"Java Eiland","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/665215"},
  {"date":"2015-05-23","title":"Pacha Festival Official After Party","venue":"Air","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/709258"},
  {"date":"2015-06-05","title":"Fame presents LOCK! Feat. Sander Kleinenberg","venue":"Fame","city":"Tokyo","country":"Japan","sourceUrl":"https://ra.co/events/717785"},
  {"date":"2015-06-20","title":"Blue Moon Festival","venue":"Park van Luna","city":"All","country":"Netherlands","sourceUrl":"https://ra.co/events/710471"},
  {"date":"2015-07-11","title":"XO - Extrema Outdoor 2015","venue":"Aquabest","city":"Eindhoven","country":"Netherlands","sourceUrl":"https://ra.co/events/703905"},
  {"date":"2015-07-26","title":"Sander Kleinenberg / Saint Glock / Matt Mccue","venue":"Verboten","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/738746"},
  {"date":"2015-07-31","title":"Realmusic Events presents Sander Kleinenberg","venue":"Kingdom Nightclub","city":"Austin","country":"United States of America","sourceUrl":"https://ra.co/events/735770"},
  {"date":"2015-08-07","title":"Konnekted presents Sander Kleinenberg at Audio","venue":"Audio SF","city":"San Francisco/Oakland","country":"United States of America","sourceUrl":"https://ra.co/events/743369"},
  {"date":"2015-08-07","title":"Sander Kleinenberg & Denney","venue":"Audio SF","city":"San Francisco/Oakland","country":"United States of America","sourceUrl":"https://ra.co/events/739163"},
  {"date":"2015-08-15","title":"Sander Kleinenberg","venue":"The Bow","city":"Buenos Aires","country":"Argentina","sourceUrl":"https://ra.co/events/736471"},
  {"date":"2015-09-24","title":"[CANCELLED] Sander Kleinenberg London DJ Residency","venue":"TBA - London","city":"London","country":"United Kingdom","sourceUrl":"https://ra.co/events/720330"},
  {"date":"2015-09-26","title":"Must Kurhaus","venue":"Must Kurhaus","city":"The Hague","country":"Netherlands","sourceUrl":"https://ra.co/events/758954"},
  {"date":"2015-10-29","title":"[CANCELLED] Sander Kleinenberg London DJ Residency","venue":"TBA - London","city":"London","country":"United Kingdom","sourceUrl":"https://ra.co/events/720541"},
  {"date":"2015-11-21","title":"Dance Festival Breda","venue":"Chasse Theater","city":"All","country":"Netherlands","sourceUrl":"https://ra.co/events/775206"},
  {"date":"2015-12-31","title":"New Year's Noir 2016","venue":"Verboten","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/777725"},
  {"date":"2015-12-31","title":"Together As One NYE 2016","venue":"Oak Canyon Ranch","city":"Orange County","country":"United States of America","sourceUrl":"https://ra.co/events/782086"},
  {"date":"2016-01-02","title":"Sander Kleinenberg [New Year's Noir 2016]","venue":"Verboten","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/779757"},
  {"date":"2016-02-13","title":"Goldfish Live, Sander Kleinenberg & Dimmi","venue":"Zig Zag","city":"Paris","country":"France","sourceUrl":"https://ra.co/events/796679"},
  {"date":"2016-03-19","title":"Sander Kleinenberg with Medcinne","venue":"Ethics Music Lounge","city":"Austin","country":"United States of America","sourceUrl":"https://ra.co/events/808828"},
  {"date":"2016-04-01","title":"[CANCELLED] Sander Kleinenberg / Saint Glock","venue":"Verboten","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/812637"},
  {"date":"2016-05-29","title":"Summer Session with Sander Kleinenberg // A Dance Party","venue":"House of Yes","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/840644"},
  {"date":"2016-06-25","title":"Sound presents Sander Kleinenberg","venue":"Sound","city":"Los Angeles","country":"United States of America","sourceUrl":"https://ra.co/events/852912"},
  {"date":"2016-07-08","title":"Sander Kleinenberg and Go Freek","venue":"Love and Propaganda","city":"San Francisco/Oakland","country":"United States of America","sourceUrl":"https://ra.co/events/843938"},
  {"date":"2016-07-10","title":"Sander Kleinenberg","venue":"Soundcheck","city":"Washington DC","country":"United States of America","sourceUrl":"https://ra.co/events/845626"},
  {"date":"2016-07-23","title":"Sound presents Sander Kleinenberg, Teemid & Bones","venue":"Sound","city":"Los Angeles","country":"United States of America","sourceUrl":"https://ra.co/events/859033"},
  {"date":"2016-07-30","title":"Afterlife with Sander Kleinenberg","venue":"Annex Night Club","city":"Chicago","country":"United States of America","sourceUrl":"https://ra.co/events/846710"},
  {"date":"2016-08-12","title":"Das Energi Festival","venue":"The Saltair","city":"Utah","country":"United States of America","sourceUrl":"https://ra.co/events/831741"},
  {"date":"2016-08-26","title":"Project301 with Sander Kleinenberg","venue":"301","city":"El Paso","country":"United States of America","sourceUrl":"https://ra.co/events/856849"},
  {"date":"2016-08-27","title":"Sound presents Sander Kleinenberg & Croatia Squad","venue":"Sound","city":"Los Angeles","country":"United States of America","sourceUrl":"https://ra.co/events/859041"},
  {"date":"2016-09-03","title":"Pacha Festival Amsterdam 2016","venue":"Arenapark","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/813620"},
  {"date":"2016-10-20","title":"Global Underground 'Twenty with James Lavelle, Darren Emerson, Dave Seaman and Many More","venue":"Q-Factory","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/863667"},
  {"date":"2016-12-16","title":"Sander Kleinenberg all Night Extended set","venue":"House of Yes","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/907632"},
  {"date":"2016-12-17","title":"Sander Kleinenberg","venue":"Halcyon","city":"San Francisco/Oakland","country":"United States of America","sourceUrl":"https://ra.co/events/908017"},
  {"date":"2016-12-31","title":"Reboot 2.0 NYE Warehouse Party","venue":"TBA - Toronto","city":"Toronto","country":"Canada","sourceUrl":"https://ra.co/events/914099"},
  {"date":"2017-01-25","title":"Sound present Sander Kleinenberg","venue":"Sound","city":"Los Angeles","country":"United States of America","sourceUrl":"https://ra.co/events/927346"},
  {"date":"2017-02-25","title":"Sound present Sander Kleinenberg","venue":"Sound","city":"Los Angeles","country":"United States of America","sourceUrl":"https://ra.co/events/933206"},
  {"date":"2017-03-10","title":"Sander Kleinenberg all Night","venue":"House of Yes","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/934737"},
  {"date":"2017-03-17","title":"Afterglow: Sander Kleinenberg","venue":"Soundcheck","city":"Washington DC","country":"United States of America","sourceUrl":"https://ra.co/events/935511"},
  {"date":"2017-03-18","title":"Sander Kleinenberg & Mike Vale at Afterlife","venue":"Annex Night Club","city":"Chicago","country":"United States of America","sourceUrl":"https://ra.co/events/929411"},
  {"date":"2017-03-24","title":"Ultra Music Festival","venue":"Bayfront Park","city":"Miami","country":"United States of America","sourceUrl":"https://ra.co/events/950922"},
  {"date":"2017-05-06","title":"Sander Kleinenberg","venue":"Pepper Club","city":"Shenzhen","country":"China","sourceUrl":"https://ra.co/events/961503"},
  {"date":"2017-06-24","title":"Sound presents Sander Kleinenberg and Lee Wells","venue":"Sound","city":"Los Angeles","country":"United States of America","sourceUrl":"https://ra.co/events/981329"},
  {"date":"2017-07-08","title":"Sander Kleinenberg All Night","venue":"House of Yes","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/979103"},
  {"date":"2017-08-19","title":"Nora En Pure with Sander Kleinenberg, Teemid","venue":"Exchange LA","city":"Los Angeles","country":"United States of America","sourceUrl":"https://ra.co/events/981409"},
  {"date":"2017-08-25","title":"Provocateur","venue":"Provocateur Dubai","city":"Dubai","country":"United Arab Emirates","sourceUrl":"https://ra.co/events/1002504"},
  {"date":"2017-09-16","title":"Fabulous with Sander Kleinenberg All Night","venue":"House of Yes","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/1011778"},
  {"date":"2017-10-28","title":"House of Hallucinations","venue":"House of Yes","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/1021443"},
  {"date":"2017-12-09","title":"Sander Kleinenberg","venue":"Spybar","city":"Chicago","country":"United States of America","sourceUrl":"https://ra.co/events/1021961"},
  {"date":"2018-01-19","title":"5 Years of Sound: Sander Kleinenberg and Lee Wells","venue":"Sound","city":"Los Angeles","country":"United States of America","sourceUrl":"https://ra.co/events/1061697"},
  {"date":"2018-05-20","title":"7th Sunday Festival 2018 - Official","venue":"Veghel","city":"All","country":"Netherlands","sourceUrl":"https://ra.co/events/1088665"},
  {"date":"2018-06-16","title":"Mermaid Parade After Party with Sander Kleinenberg","venue":"House of Yes","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/1111903"},
  {"date":"2018-06-22","title":"Deep Space presents: Sander Kleinenberg","venue":"1 OAK LA","city":"Los Angeles","country":"United States of America","sourceUrl":"https://ra.co/events/1126581"},
  {"date":"2018-06-24","title":"Deep Space After Dark: Sander Kleinenberg","venue":"Sound","city":"Los Angeles","country":"United States of America","sourceUrl":"https://ra.co/events/1126547"},
  {"date":"2018-07-21","title":"The 5th Summer of Love - Sold Out","venue":"Thuishaven","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/1044506"},
  {"date":"2018-08-17","title":"Sander Kleinenberg","venue":"Site 1A","city":"Milwaukee","country":"United States of America","sourceUrl":"https://ra.co/events/1133130"},
  {"date":"2018-08-18","title":"Cirque Nouveau with Sander Kleinenberg (All Night Long)","venue":"House of Yes","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/1139865"},
  {"date":"2018-09-01","title":"Valtifest","venue":"Thuishaven","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/1132996"},
  {"date":"2018-10-20","title":"Blood Night with Sander Kleinenberg All Night","venue":"House of Yes","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/1168422"},
  {"date":"2018-10-21","title":"The Nightwriters","venue":"Escape Studio","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/1157870"},
  {"date":"2018-12-31","title":"Bang Bang NYE","venue":"The Butcher Social Club","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/1196062"},
  {"date":"2019-01-04","title":"U11 One Year vol.1 with Sander Kleinenberg","venue":"Serdce Bar","city":"Krasnodar","country":"Russia","sourceUrl":"https://ra.co/events/1201708"},
  {"date":"2019-04-12","title":"Sander Kleinenberg at The Midway","venue":"The Midway","city":"San Francisco/Oakland","country":"United States of America","sourceUrl":"https://ra.co/events/1241735"},
  {"date":"2019-04-19","title":"Earth Night with Sander Kleinenberg, Nickodemus & More","venue":"House of Yes","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/1233181"},
  {"date":"2019-06-08","title":"The Promised Land 6th Anniversary","venue":"TBA - Netherlands","city":"All","country":"Netherlands","sourceUrl":"https://ra.co/events/1198521"},
  {"date":"2019-06-15","title":"Sander Kleinenberg","venue":"House of Yes","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/1266047"},
  {"date":"2019-06-16","title":"Wavy Sunday Pool Party w Sander Kleinenberg","venue":"Eptx Luchador","city":"El Paso","country":"United States of America","sourceUrl":"https://ra.co/events/1338855"},
  {"date":"2019-10-12","title":"Sander Kleinenberg All Night Long","venue":"House of Yes","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/1310817"},
  {"date":"2019-10-19","title":"HYPNOSIS 30TH ANNIVERSARY: PAUL OAKENFOLD AND MARKUS SCHULZ","venue":"Albert Hall","city":"Manchester","country":"United Kingdom","sourceUrl":"https://ra.co/events/1305837"},
  {"date":"2020-02-01","title":"Sound presents Sander Kleinenberg & Shanto (Cancelled)","venue":"Sound","city":"Los Angeles","country":"United States of America","sourceUrl":"https://ra.co/events/1368679"},
  {"date":"2020-02-08","title":"Sander Kleinenberg All Night Long","venue":"House of Yes","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/1379204"},
  {"date":"2020-02-15","title":"Winter Wooferland with Sander Kleinenberg, Dimitri, Alexander Koning and More","venue":"Paradiso","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/1362010"},
  {"date":"2024-03-22","title":"Sander Kleinenberg","venue":"House of Yes","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/1870202"},
  {"date":"2024-05-25","title":"SANDER KLEINENBERG AT PARAISO ESTEREO by WERK","venue":"Paraiso Estereo","city":"Miami","country":"United States of America","sourceUrl":"https://ra.co/events/1923141"},
  {"date":"2024-07-05","title":"Destination SXM: Ibiza with Julian Prince, Kadosh, Nicolas Masseyeff, Oxia & Sander Kleinenberg","venue":"Akasha Las Dalias Club - Ibiza","city":"Ibiza","country":"Spain","sourceUrl":"https://ra.co/events/1939449"},
  {"date":"2024-08-09","title":"Destination SXM: Ibiza with Julian Prince, Kadosh, Magit Cacoon, Sander Kleinenberg & Wild Dark","venue":"Akasha Las Dalias Club - Ibiza","city":"Ibiza","country":"Spain","sourceUrl":"https://ra.co/events/1963859"},
  {"date":"2024-08-31","title":"31 AUG - Thuishaven with Tinlicker 3 hours","venue":"Thuishaven","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/1921245"},
  {"date":"2024-09-05","title":"Destination SXM: Ibiza with Julia Sandstorm, Kadosh, Sander Kleinenberg, Vito","venue":"Akasha Las Dalias Club - Ibiza","city":"Ibiza","country":"Spain","sourceUrl":"https://ra.co/events/1990282"},
  {"date":"2024-10-17","title":"Destination SXM: ADE, with Themba & Sander Kleinenberg","venue":"Cafe in the City","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/2021457"},
  {"date":"2024-11-16","title":"Floorplay presents 'This Is Sander' with Sander Kleinenberg, Alex Meza, Brian-S, Paul Sparkes","venue":"Loods 12","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/2033569"},
  {"date":"2025-01-04","title":"The Promised land, The Beginning & I Love House Classics pres. 'De Nieuwjaarsborrel 2025'","venue":"Thuishaven","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/1997503"},
  {"date":"2025-01-24","title":"The Six Pm Club","venue":"Jimmy Woo","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/2064927"},
  {"date":"2025-03-12","title":"SXM Festival 2025","venue":"Happy Bay Beach","city":"All","country":"Saint Martin","sourceUrl":"https://ra.co/events/2041675"},
  {"date":"2025-03-22","title":"Sweet Nectar Presets Better Together w Sander Kleinenberg","venue":"Massilia","city":"Los Angeles","country":"United States of America","sourceUrl":"https://ra.co/events/2118777"},
  {"date":"2025-04-19","title":"Madam by Night invites: Sander Kleinenberg, Thomas Robson","venue":"Madam","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/2087852"},
  {"date":"2025-05-02","title":"Sander Kleinenberg + VITE - by VAGALUME, TULÚM","venue":"TBA - Vagalume Beach Club","city":"Tulum","country":"Mexico","sourceUrl":"https://ra.co/events/2148391"},
  {"date":"2025-05-03","title":"Sander Kleinenberg + Fer Romano + Josta","venue":"Fünk","city":"Mexico City","country":"Mexico","sourceUrl":"https://ra.co/events/2158549"},
  {"date":"2025-05-09","title":"De Clubnacht (with Sander Kleinenberg)","venue":"Podium Victorie","city":"All","country":"Netherlands","sourceUrl":"https://ra.co/events/2080029"},
  {"date":"2025-05-16","title":"Temple presentes Sander Kleinenberg","venue":"TEMPLE","city":"Lisbon","country":"Portugal","sourceUrl":"https://ra.co/events/2120732"},
  {"date":"2025-06-06","title":"Sander Kleinenberg with Sherif + Aledro","venue":"Magic Stick","city":"Detroit","country":"United States of America","sourceUrl":"https://ra.co/events/2161905"},
  {"date":"2025-07-18","title":"Sander Kleinenberg","venue":"SILO","city":"New York City","country":"United States of America","sourceUrl":"https://ra.co/events/2182954"},
  {"date":"2025-08-16","title":"Berlin presents Sander Kleinenberg","venue":"Carat's Cafe & Bar","city":"Brighton","country":"United Kingdom","sourceUrl":"https://ra.co/events/2204523"},
  {"date":"2025-08-23","title":"Valtifest 2025 - Oerknal","venue":"Kaap Amsterdam","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/2203337"},
  {"date":"2025-09-20","title":"Avant Garde with Sander Kleinenberg","venue":"Paal69","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/2257967"},
  {"date":"2025-10-04","title":"Summer of Love pres. Autumn Love Maassilo","venue":"Maassilo","city":"Rotterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/2144670"},
  {"date":"2025-10-17","title":"HOUSE LEGACY invites Sander Kleinenberg","venue":"Panama","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/2271071"},
  {"date":"2025-11-08","title":"Wooferland, The Beginning, The promised Land and Rave Tribe pres. The Rave Game 2.0","venue":"Thuishaven","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/2172578"},
  {"date":"2026-01-16","title":"Hostel Hide Out","venue":"Onder Hans","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/2342406"},
  {"date":"2026-03-07","title":"Wooferland, Summer of Love & The beginning pres. 'Het Wintercircus' 10 year Anni on Thuishaven","venue":"Thuishaven","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/2305350"},
  {"date":"2026-05-08","title":"IOOI presents: Sander Kleinenberg","venue":"Iocerouno","city":"Monterrey","country":"Mexico","sourceUrl":"https://ra.co/events/2417458"},
  {"date":"2026-05-24","title":"10 yrs of Pand 13 presents Samuel Deep & Sander Kleinenberg","venue":"Houtbaar Haarlem","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/2409598"},
  {"date":"2026-06-20","title":"Tide","venue":"Paal69","city":"Amsterdam","country":"Netherlands","sourceUrl":"https://ra.co/events/2453837"},
];
